### PR TITLE
Parse escaped colons in class names correctly

### LINKED ISSUE #411: Floki.find doesn't support escaped colons in class names
## Description

Floki doesn't support selectors with escaped colons in them, probably it's mixing them up with pseudo selectors

## To Reproduce

- Using Floki v0.33.1
- Using Elixir v1.13.3
- Using Erlang OTP v24
- With this code:

```elixir
 > Floki.find(document, "a.xs\\:red-500")
[] 
```

## Expected behavior
```elixir
 > Floki.find(document, "a.xs\\:red-500")
[{"a", [{"class", "xs\\:red-500"}], ["I'm a link with a funny selector"]}]
```

The current workaround is to use `a[class="xs:red-500"]`

### PR DESCRIPTION
**Pull request by viniciusmuller**
This pull requests adds an extra rule in the parser in order to prevent escaped class names (`a.xs\\:red-500`) from being parsed as  pseudo selectors.

Closes #411

### CODE REVIEW

**Comment by philss** [comment]
@viniciusmuller thank you!! :purple_heart:

File: test/floki/selector/parser_test.exs [hunk 1]
```diff
@@ -22,6 +22,14 @@ defmodule Floki.Selector.ParserTest do
     end
   end
 
+  test "escaped colons in class names" do
+    tokens = tokenize("a.xs\\:red-500")
+
+    assert Parser.parse(tokens) == [
+             %Selector{type: "a", classes: ["xs\\:red-500"], pseudo_classes: []}
```
Comment (viniciusmuller) [inline test/floki/selector/parser_test.exs:29]: @philss I was thinking here, do you think that this is the expected behavior? Or we actually want to return "xs:red-500", I did this based on the original issue, but maybe the author made a typo in the example code

Comment (philss) [reply test/floki/selector/parser_test.exs:29]: @viniciusmuller I did a quick fix in #464 

I believe the author was trying to find elements with Tailwind classes, which can have colons in it.
